# Generated by Django 5.1.15 on 2026-10-04 04:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('web', models.URLField(blank=True)),
                ('notas', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('por_postular', 'Por postular'), ('enviada', 'Enviada'), ('captcha_pendiente', 'Captcha pendiente'), ('error', 'Error'), ('saltada', 'Saltada'), ('vista', 'Vista por la empresa'), ('entrevista', 'Entrevista'), ('oferta', 'Oferta'), ('rechazada', 'Rechazada')], default='por_postular', max_length=20)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('cv_pdf', models.CharField(blank=True, max_length=500)),
                ('keywords_usadas', models.JSONField(blank=True, default=list)),
                ('captcha_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('screenshot', models.CharField(blank=True, max_length=500, null=True)),
                ('notas', models.TextField(blank=True)),
                ('brechas', models.TextField(blank=True)),
                ('proxima_accion', models.CharField(blank=True, max_length=300)),
                ('proximo_seguimiento', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'postulaciones',
                'ordering': ['-fecha_envio', '-creado'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('correo_recibido', 'Correo recibido'), ('correo_enviado', 'Correo enviado'), ('cambio_estado', 'Cambio de estado'), ('entrevista', 'Entrevista agendada'), ('nota', 'Nota')], default='nota', max_length=20)),
                ('titulo', models.CharField(blank=True, max_length=300)),
                ('remitente', models.CharField(blank=True, max_length=300)),
                ('contenido', models.TextField(blank=True)),
                ('estado_anterior', models.CharField(blank=True, max_length=20)),
                ('estado_nuevo', models.CharField(blank=True, max_length=20)),
                ('actor', models.CharField(default='sistema', max_length=100)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('postulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='tracker.postulacion')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.CharField(max_length=300)),
                ('url', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('ats', models.CharField(choices=[('ashby', 'Ashby'), ('greenhouse', 'Greenhouse'), ('lever', 'Lever'), ('jazzhr', 'JazzHR'), ('workday', 'Workday'), ('getonbrd', 'Get on Board'), ('linkedin', 'LinkedIn'), ('generico', 'Genérico')], default='generico', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('salario_min', models.IntegerField(blank=True, null=True)),
                ('salario_max', models.IntegerField(blank=True, null=True)),
                ('moneda', models.CharField(blank=True, max_length=50)),
                ('modalidad', models.CharField(blank=True, max_length=120)),
                ('contrato', models.CharField(blank=True, max_length=200)),
                ('fuente', models.CharField(blank=True, max_length=200)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('prioridad', models.PositiveSmallIntegerField(default=3)),
                ('estado', models.CharField(choices=[('nueva', 'Por revisar'), ('por_postular', 'Aprobada / por postular'), ('procesada', 'Procesada'), ('descartada', 'Descartada')], default='nueva', max_length=20)),
                ('fecha_detectada', models.DateTimeField(default=django.utils.timezone.now)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacantes', to='tracker.empresa')),
            ],
            options={
                'ordering': ['-fecha_detectada'],
            },
        ),
        migrations.AddField(
            model_name='postulacion',
            name='vacante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='postulacion', to='tracker.vacante'),
        ),
        migrations.CreateModel(
            name='CVGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta_pdf', models.CharField(max_length=500)),
                ('keywords_usadas', models.JSONField(blank=True, default=list)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('vacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to='tracker.vacante')),
            ],
            options={
                'verbose_name': 'CV generado',
                'verbose_name_plural': 'CVs generados',
                'ordering': ['-fecha'],
            },
        ),
    ]
